simil={     'SHIB-USD':'Shiba Inu',
            'DOT-USD':'Polkadot',
            'REQ-USD':'Request',
            'ZRX-USD':'0x',
            'MIR-USD':'Mirror Protocol',
            'RNDR-USD':'Render Token',
            'USDT-USD':'Tether',
            # 'SKL-USD':'SKl',
            'SOL-USD':'Solana',
            'AVAX-USD':'Avalanche',
            'OCEAN-USD':'Ocean Protocol',   
            'INJ-USD':'Injective',
            'XLM-USD':'Stellar',
            'ENJ-USD':'Enjin Coin',
            'ZIL-USD':'Zilliqa',
            'FIL-USD':'Filecoin',
            'ICP-USD':'Internet Computer',
            'PAXG-USD':'Pax Gold',
            'UMA-USD':'UMA',
            'NEO-USD':'NEO',
            'PLA-USD':'PlayDapp',
            'ICX-USD':'ICON',
            'CRO-USD':'cronos',
            'IMX-USD':'Immutable-X',
            'AMP-USD':'Amp',
            'YGG-USD':'Yield Guild Games',
            'KAVA-USD':'Kava',
            'COMP-USD':'Compound',
            'TRX-USD':'TRON',
            'REN-USD':'REN',
            'BADGER-USD':'Badger DAO',
            'QUICK-USD':'Quickswap',
            'LTC-USD':'Litecoin',
            'LSK-USD':'Lisk',
            'DUSK-USD':'Dusk Network',
            'XTZ-USD':'Tezos',
            'DGB-USD':'DigiByte',
            'UNI-USD':'Uniswap',
            'THETA-USD':'THETA',
            'APE-USD':'ApeCoin',
            'CRV-USD':'Curve DAO Token',
            'CHZ-USD':'Chiliz',
            'SAND-USD':'The Sandbox',
            'KNC-USD':'Kyber Network Crystal V2',
            'CLV-USD':'clover',
            'AAVE-USD':'Aave',
            'TRIBE-USD':'Tribe',
            'ARPA-USD':'Arpa Chain',
            'ETC-USD':'Ethereum Classic',
            'MKR-USD':'Maker',
            'RLC-USD':'RLC',
            'ADA-USD':'Cardano',
            'BCH-USD':'Bitcoin Cash',
            'VGX-USD':'Voyager Token',
            'WAX-USD':'WAX',
            'MATIC-USD':'Polygon',
            'AXS-USD':'Axie Infinity',
            'REP-USD':'Augur',
            'MASK-USD':'Mask Network',
            'DASH-USD':'Dash',
            'NMR-USD':'Numeraire',
            'LPT-USD':'Livepeer',
            'COTI-USD':'COTI',
            'LRC-USD':'Loopring',
            'ALGO-USD':'Algorand',
            'STORJ-USD':'Storj',
            'SNX-USD':'Synthetix',
            'MLN-USD':'Enzyme',
            'AUCTION-USD':'Bounce Token',
            'NEXO-USD':'Nexo',
            'LINK-USD':'Chainlink',
            'XVG-USD':'Verge',
            'BOND-USD':'Bondly',
            'ZEC-USD':'Zcash',
            'LUNA-USD':'Terra',
            'MOB-USD':'MobileCoin',
            'VET-USD':'VeChain',
            'WAVES-USD':'Waves',
            'XMR-USD':'Monero',
            'DOGE-USD':'Dogecoin',
            'FORTH-USD':'Ampleforth Governance Token',
            'EOS-USD':'EOS',
            'SUSHI-USD':'SushiSwap',
            'SRM-USD':'Serum',
            'BNT-USD':'Bancor',
            'ETH-USD':'Ethereum',
            'ZEN-USD':'Horizen',
            'BAT-USD':'Basic Attention Token',
            'FTM-USD':'Fantom',
            'ATOM-USD':'Cosmos',
            'PERP-USD':'Perpetual Protocol',
            'GALA-USD':'Gala',
            'BTC-USD':'Bitcoin',
            'XRP-USD':'XRP',
            'ORN-USD':'Orion Protocol',
            'STX-USD':'Stacks',
            'DCR-USD':'Decred',
            'REEF-USD':'Reef',
            'BAND-USD':'Band Protocol',
            'KSM-USD':'Kusama',
            'RUNE-USD':'THORChain',
            'BTS-USD':'BitShares',
            'BTT-USD':'BitTorrent-New',
            'BZRX-USD':'bZx Protocol',
            'BUSD-USD':'Binance USD',
            'YFI-USD':'yearn finance',
            'HNT-USD':'Helium',
            'HBAR-USD':'Hedera',
            'CELO-USD':'Celo',
            'MANA-USD':'Decentraland',
            'CVC-USD':'Civic'
            }
coins=['SHIB','DOT','REQ','ZRX','MIR','RNDR','USDT','SOL','AVAX','OCEAN','INJ','XLM','ENJ','ZIL','FIL','ICP','PAXG','UMA','NEO','PLA','ICX','CRO','IMX','AMP','YGG','KAVA','COMP','TRX','REN','BADGER','QUICK','LTC','LSK','DUSK','XTZ','DGB','UNI','THETA','APE','CRV','CHZ','SAND','KNC','CLV','AAVE','TRIBE','ARPA','ETC','MKR','RLC','ADA','BCH','VGX','WAX','MATIC','AXS','REP','MASK','DASH','NMR','LPT','COTI','LRC','ALGO','STORJ','SNX','MLN','AUCTION','NEXO','LINK','XVG','BOND','ZEC','LUNA','MOB','VET','WAVES','XMR','DOGE','FORTH','EOS','SUSHI','SRM','BNT','ETH','ZEN','BAT','FTM','ATOM','PERP','GALA','BTC','XRP','ORN','STX','DCR','REEF','YFI','MANA','CVC']
dt1=['>$1000','$100  -   $1000','$10   -   $100','$1  -  $10','$0.1 -  $1','<$0.1']
dt2=['>$10 Billion','$1 Billion - $10 Billion','$100 million - $1 Billion','$10 Million - $100 Million','$1 Million - $10 Million','<$1 Million']
dt3=['> 5 years','2 years - 5 years','1 years - 2 years','1 year - 6 Months','6 Months - 3 Months','< 3 Months']
dt4=['Daily Trader(days-weeks)','Investor (months-year)']
dt5=['High Risk  - High Reward','Low Risk  - Low Reward']

